version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ADMIN_CREDENTIALS: ${ADMIN_CREDENTIALS}
      BASE_URL: ${BASE_URL}
    ports:
      - "5040:5040"
    volumes:
      - .:/app:delegated
    command: gunicorn -w 2 -b 0.0.0.0:5040 wsgi:app

volumes:
  db_data:
